// <auto-generated />
using IotProject.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IotProject.DataAccess.Migrations
{
    [DbContext(typeof(IotProjectDbContext))]
    [Migration("20210827075947_initialCreate")]
    partial class initialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IotProject.Entities.Teamcity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("branch_display_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("branch_is_default")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("branch_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("build_event")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("build_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("build_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("build_result")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("build_result_delta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("build_result_previous")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("build_start_time")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("build_status_url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("timestamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("triggered_by")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teamcities");
                });
#pragma warning restore 612, 618
        }
    }
}
